version: "3.8"
services:
    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - 5432:5432

    app:
        build: .
        env_file:
            - .env
        volumes:
            - ${PWD:-./}:/app
        ports:
            - ${APP_PORT}:8000
        command: sh -c "sleep 10 && npm install && npm run build && npm run seed && npm run start"
        depends_on:
            - db

    maildev:
        image: maildev/maildev
        ports:
            - "8025:1080"
            - "25:1025"
